language: node_js
node_js:
  - "node"

script:
  # Yarn Tests
  - yarn test

  # Inferno Tests
  - rvm install ruby --latest
  - git clone --single-branch -b development https://github.com/siteadmin/inferno.git
  - cd inferno
  - bundle install
  - yarn start &
  - rake inferno:execute[http://localhost:3000,Conformance]